### ISSUE TITLE
StripePaymentAccount parent controller has a new constructor

### ISSUE THREAD

**Issue by Onein** [pickware/ShopwareStripePayment#116] opened 2022-05-24 11:41 UTC
The Shopware_Controllers_Frontend_Account controller has a new constructor:
```
public function __construct(Shopware_Components_Config $config, CaptchaValidator $captchaValidator)
```
This results in an user facing error when navigating to the account credit card section, because the plugin extends the mentioned controller.

**Comment by grosssmutttr** [comment] 2022-06-29 10:38
PUSH!

**Comment by svenmuennich** [comment] 2022-07-06 19:16
Duplicate of https://github.com/pickware/ShopwareStripePayment/issues/118

**Closed by svenmuennich** 2022-07-06 19:16 UTC
